import { Video } from '../types';

export const INITIAL_MOCK_VIDEOS: Video[] = [
  {
    id: 'mock-1',
    title: 'Building a Microservice Architecture with NestJS and PostgreSQL',
    description: 'Learn how to architect high-performance microservices using NestJS, TypeORM, Docker, and standard REST inter-service communication protocols.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&auto=format&fit=crop&q=60',
    userId: 'user-mock-1',
    channelName: 'JunaidTech Microservices',
    channelAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    viewsCount: 142500,
    likesCount: 8420,
    dislikesCount: 120,
    commentsCount: 342,
    createdAt: new Date(Date.now() - 3600000 * 24 * 3).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-2',
    title: 'React 19 & Next.js 15 Full Crash Course - Master Web Development',
    description: 'Everything you need to know about React Server Components, Server Actions, and modern UI engineering principles.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=60',
    userId: 'user-mock-2',
    channelName: 'CodeWithJunaid',
    channelAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    viewsCount: 984000,
    likesCount: 45100,
    dislikesCount: 530,
    commentsCount: 1890,
    createdAt: new Date(Date.now() - 3600000 * 24 * 7).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-3',
    title: 'Docker & Kubernetes Masterclass for Backend Engineers',
    description: 'Master containerization, service discovery, compose orchestration, and zero-downtime microservices deployment.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&auto=format&fit=crop&q=60',
    userId: 'user-mock-3',
    channelName: 'DevOps & Cloud Simplified',
    channelAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    viewsCount: 312000,
    likesCount: 19800,
    dislikesCount: 210,
    commentsCount: 670,
    createdAt: new Date(Date.now() - 3600000 * 24 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mock-4',
    title: 'PostgreSQL Database Performance Tuning & Query Optimization',
    description: 'Deep dive into indexes, EXPLAIN ANALYZE, connection pooling, and optimizing TypeORM queries for heavy traffic.',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&auto=format&fit=crop&q=60',
    userId: 'user-mock-4',
    channelName: 'Database Mastery',
    channelAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    viewsCount: 54100,
    likesCount: 3400,
    dislikesCount: 45,
    commentsCount: 128,
    createdAt: new Date(Date.now() - 3600000 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
